// Generated by Wrangler on Fri Mar 08 2024 22:34:59 GMT+0800 (China Standard Time)
// by running `wrangler types`

export {}
declare global {
  const KV_STORE: KVNamespace
  const ENABLED_R2: 'yes'
  const R2_BUCKET: R2Bucket
}
