import { fileURLToPath } from 'node:url'

import { fs, path } from 'zx'
import dedent from 'dedent'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const publicDir = path.join(__dirname, '..', 'public')
const publicAssetsTsPath = path.join(__dirname, '..', 'src/worker/static-assets/public.ts')

export async function getPublicStats() {
  const fsDirentData = await fs.readdir(publicDir, { withFileTypes: true })
  return fsDirentData
}

export async function generatePublicAssetsTs(fsDirentData: fs.Dirent[]) {
  const result = await fs.writeFile(
    publicAssetsTsPath,
    dedent`
      // Generated by /scripts/public-assets.ts
      export const publicAssets = ${JSON.stringify(fsDirentData.map((item) => {
          return item.isDirectory() ? `/${item.name}/` : `/${item.name}`
      }))}
    `,
    { encoding: 'utf-8' },
  )
  return result
}

export async function main() {
  const fsDirentData = await getPublicStats()
  await generatePublicAssetsTs(fsDirentData)
}

main()
